version: 2.1
commands:
  install-bazel:
    steps:
      - run:
          name: Install bazel and RBE credential
          command: |
            # Install bazel
            curl -OL https://github.com/bazelbuild/bazel/releases/download/0.20.0/bazel-0.20.0-installer-linux-x86_64.sh
            chmod +x bazel-0.20.0-installer-linux-x86_64.sh
            sudo ./bazel-0.20.0-installer-linux-x86_64.sh

            # Install RBE credential
            bazel run @graknlabs_build_tools//ci:install-bazel-rbe-credential

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: |
            bazel run @graknlabs_build_tools//ci:run-bazel-rbe << parameters.command >>

  run-grakn-server:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run:
          name: ./grakn server start
          command: |
            mkdir dist
            tar -xvzf bazel-bin/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
            nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run-bazel-rbe:
          command: bazel build //...

  test:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run-grakn-server
      - run: ./dist/grakn-core-all-linux/grakn console -f `pwd`/tests/support/basic-genealogy.gql -k gene
      - run: bazel test //:test-integration --test_output=streamed

  test-deployment:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run: sudo apt install -y expect
      - run: bazel run //:deploy-npm -- test $REPO_GRAKN_USERNAME $REPO_GRAKN_PASSWORD $REPO_GRAKN_EMAIL
      - run-grakn-server
      - run: |
          cd tests/deployment/
          sed -i -e "s/SNAPSHOT/$CIRCLE_SHA1/g" VERSION
          npm install http://repo.grakn.ai/repository/test-npm-group/grakn-client/-/grakn-client-$(cat VERSION).tgz
          npm install jest
          jest nodeApplicationTest.js

  sync-dependencies:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run: |
          # sync-dependencies for client-nodejs relies on //:deploy-npm having been called in a previous job (test-deployment)
          bazel run @graknlabs_build_tools//ci:sync-dependencies -- \
          --source client-nodejs:master \
          --targets docs:development

  release-approval:
    machine: true
    steps:
      - checkout
      - install-bazel
      - run: bazel run @graknlabs_build_tools//ci:release-approval

  release-npm:
    machine: true
    working_directory: ~/grakn
    steps:
      - checkout
      - install-bazel
      - run: bazel run //:deploy-npm -- npmjs $REPO_NPM_USERNAME $REPO_NPM_PASSWORD $REPO_NPM_EMAIL

  release-cleanup:
    machine: true
    steps:
      - checkout
      - run: git push --delete origin client-nodejs-release-branch

workflows:
  version: 2
  client-nodejs:
    jobs:
      - build
      - test
      - test-deployment:
          filters:
            branches:
              only: master
          requires:
            - build
            - test
      - sync-dependencies:
          filters:
            branches:
              only: master
          requires:
            - test-deployment
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - sync-dependencies

  # the 'client-nodejs-release' workflow is triggered by the creation of 'client-nodejs-release-branch' branch in graknlabs/client-nodejs
  # it consists of jobs which:
  # - publishes client-nodejs to npm
  # - cleans up the 'client-nodejs-release-branch' branch which was created by the release-approval job
  client-nodejs-release:
    jobs:
      - release-npm:
          filters:
            branches:
              only: client-nodejs-release-branch
      - release-cleanup:
          requires:
            - release-npm
          filters:
            branches:
              only: client-nodejs-release-branch
